[package]
name = "ufotofu"
version = "0.4.1"
edition = "2021"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/worm-blossom/ufotofu"
description = "Abstractions for lazily consuming and producing sequences"
exclude = [
    "fuzz/*",
    ".github/workflows/rust.yml",
]

[features]

default = ["std"]

# Provide functionality that relies on the std library. Enabled by default.
std = ["alloc"]

# Provide functionality that relies on dynamic memory allocation.
alloc = []

# Provide implementations for development helpers.
dev = ["dep:arbitrary"]

# Provide compatibility wrappers for the `futures` crate.
compat_futures = ["dep:futures"]

[dependencies]
arbitrary = { version = "1.0.2", features = ["derive"], optional = true}
either = "1.10.0"
ufotofu_queues = { path="../ufotofu_queues", version = "0.5.0" }
wrapper = "0.1.1"
futures = { version = "0.3.30", optional = true}

[dev-dependencies]
smol = "2.0.0"

# docs.rs-specific configuration
[package.metadata.docs.rs]
# document all features
all-features = true
